name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Ou 'master', dependendo do nome da sua branch principal

# Permissões necessárias para que a Action escreva/publique no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente por vez
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/pages-config-action@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Pasta onde estão seus arquivos estáticos ('.' significa a raiz)
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4